"""add hackatime user id to user

Revision ID: 17f95f9fc4b6
Revises: 9c14e08cc60d
Create Date: 2026-10-03 13:26:34.619577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f95f9fc4b6'
down_revision = '9c14e08cc60d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hackatime_user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hackatime_user_id')

    # ### end Alembic commands ###
