"""make seconds_spent an integer

Revision ID: 1ee8d23b359e
Revises: 7920381368c6
Create Date: 2026-10-10 15:01:16.134243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee8d23b359e'
down_revision = '7920381368c6'
branch_labels = None
depends_on = None


def upgrade():
    # leftover from the failed run (harmless if it doesn't exist)
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_devlog")

    # backfill NULL/blank values so the NOT NULL integer column can be populated
    op.execute(
        "UPDATE devlog SET seconds_spent = '0' "
        "WHERE seconds_spent IS NULL OR TRIM(seconds_spent) = ''"
    )

    with op.batch_alter_table('devlog', schema=None) as batch_op:
        batch_op.alter_column(
            'seconds_spent',
            existing_type=sa.VARCHAR(length=500),
            type_=sa.Integer(),
            existing_nullable=False,
            postgresql_using="seconds_spent::integer",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devlog', schema=None) as batch_op:
        batch_op.alter_column('seconds_spent',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###
