"""move hackatime api key to time tarcking connection

Revision ID: 7920381368c6
Revises: 17f95f9fc4b6
Create Date: 2026-10-03 14:02:03.211459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7920381368c6'
down_revision = '17f95f9fc4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_tracking_connection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_api_key', sa.String(length=200), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hackatime_api_key')
        batch_op.drop_column('hackatime_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hackatime_user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('hackatime_api_key', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('time_tracking_connection', schema=None) as batch_op:
        batch_op.drop_column('provider_api_key')

    # ### end Alembic commands ###
