"""add hackatime api key to user

Revision ID: 9c14e08cc60d
Revises: d112f34190d6
Create Date: 2026-10-02 20:18:22.823345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c14e08cc60d'
down_revision = 'd112f34190d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hackatime_api_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hackatime_api_key')

    # ### end Alembic commands ###
