"""initial migration

Revision ID: d112f34190d6
Revises: 
Create Date: 2026-10-02 20:12:53.250332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd112f34190d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hackatime_api_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hackatime_api_key', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
